Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_log/urls.py
# 导入了为项目和管理网站管理URL的函数和模块
from django.contrib import admin
from django.urls import path,include
# urlpatterns 包含项目中的应用程序的URL
urlpatterns = [
    path('admin/', admin.site.urls), # 该模块定义了可在管理网站中请求的所有URL
    path('users/',include('users.urls', namespace='users')), # 这行代码与任何以单词users打头的URL（如http://localhost:8000/users/login/） 都匹配
    path('', include('learning_logs.urls', namespace='learning_logs')), # 与书中不同 url这个方法变成了path，还有就是不需要r^等标识符。
   
]

'''
Django版本更新,书上的代码需做相应修改

书中源代码：
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]
应改为：
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

'''

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.urls import path,re_path
from . import views

app_name='learning_logs' # 不能少 ，否则runserver的时候就会出错

# https://docs.djangoproject.com/en/2.2/ref/urls/#module-django.urls.conf
urlpatterns = [
    # 主页
    path('', views.index, name='index'),# Django将在文件views.py中查找函数index()
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    # 特定主题的详细页面
    # use a regular expression, you can use re_path(). https://stackoverflow.com/questions/47661536/django-2-0-path-error-2-0-w001-has-a-route-that-contains-p-begins-wit
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'), # ?P<topic_id> 将匹配的值存储到topic_id 中； 而表达式\d+ 与包含在两个斜杆内的任何数字都匹配， 不管这个数字为多少位。
    # 用于添加新主题的网页
    path('new_topic/', views.new_topic, name = 'new_topic'),
    # 用于添加新条目的页面
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry')

]

# urls -> views -> html  添加网页步骤

'''
Django版本更新,书上的代码需做相应修改

书中源代码：
from django.conf.urls import url
from . import views
urlpatterns = [
     # Home page.
    url(r'^$', views.index, name='index'),

    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),

    # Detail page for a single topic.
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
]

应改为：
from django.urls import path
from . import views

app_name='learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),

    # 显示所有的主题
    path('topics/', views.topics, name='topics'),

    # 特定主题的详细页面
    path("topics/(?P<topic_id>\d+)/", views.topic, name='topic'),
]

'''

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/users/urls.py
"""为应用程序users定义URL模式"""

# 非 from django.conf.urls import url
from django.urls import path,re_path
from django.contrib.auth.views import LoginView
# from django.contrib.auth.views import login  In django-2.1, the old function-based views have been removed,
from . import views

app_name= 'users'# 不能少

urlpatterns = [
    # 登录页面
    # re_path(r'^login/$', login, {'template_name': 'users/login.html'},name='login'),
    re_path(r'^login/$',LoginView.as_view(template_name='users/login.html'),name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    # 注册页面
    re_path(r'^register/$', views.register, name='register'), # 与URL http://localhost:8000/users/register/匹配， 并将请求发送给我们即将编写的函数register()
]

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File    :   models.py
@Time    :   2019/04/28 22:23:15
@Author  :   leacoder
@Version :   1.0
@Contact :   leacock1991@gmail.com
@License :   
@Desc    :   我们导入了模块models， 还让我们创建自己的模型。 模型告诉Django如何处理应用程序中存储的数据。 在代码层面， 模型就是一个类，  包含属性
和方法。 
'''

# here put the import lib

from django.db import models
from django.contrib.auth.models import User # 导入了django.contrib.auth 中的模型User ， 然后在Topic 中添加了字段owner ， 它建立到模型User 的外键关系

# Create your models here. # 在这里创建模型
# 创建了一个名为Topic 的类， 它继承了Model ——Django中一个定义了模型基本功能的类。
class Topic(models.Model):
    ''' 用户学习的主题'''
    # https://docs.djangoproject.com/en/2.2/ref/models/fields/#charfield
    text = models.CharField(max_length = 200) # 属性text是一个CharField——由字符或文本组成的数据
    # https://docs.djangoproject.com/en/2.2/ref/models/fields/#datetimefield
    date_added = models.DateTimeField(auto_now_add=True) # 实参auto_add_now=True 让Django将这个属性自动设置成当前日期和时间。
    owner = models.ForeignKey(User,on_delete=models.CASCADE) # 
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

# Entry 也继承了Django基类Model
class Entry(models.Model):
    '''学到的有关某个主题的具体知识'''
    # 外键是一个数据库术语， 它引用了数据库中的另一条记录； 这些代码将每个条目关联到特定的主题。 每个主题创建时， 都给它分配了一个键（或ID） 。 
    # https://docs.djangoproject.com/en/2.2/ref/models/fields/#foreignkey
    # 注 在django2.0后定义外键和一对一关系的时候需要加on_delete选项
    topic = models.ForeignKey("Topic",on_delete=models.CASCADE)
    '''
    书中源代码：
        topic = models.ForeignKey(Topic)
    应改为：
        topic = models.ForeignKey("Topic",on_delete=models.CASCADE)
    '''
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # 在Entry 类中嵌套了Meta 类。 Meta 存储用于管理模型的额外信息， 在这里， 它让我们能够设置一个特殊属性， 让Django在需要时使用Entries 来表示多个条目。 
    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.text) > 50:
            return self.text[:50] + "..." # 由于条目包含的文本可能很长， 我们让Django只显示text 的前50个字符
        else:
            return self.text

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic,Entry

# 让用户输入并提交信息的页面都是表单， 那怕它看起来不像表单。
# 创建表单的最简单方式是使用ModelForm， 它根据我们在第18章定义的模型中的信息自动创建表单。
class TopicForm(forms.ModelForm): # 定义了一个名为TopicForm 的类， 它继承了forms.ModelForm 。
    class Meta:
        model = Topic # 根据模型Topic 创建一个表单
        fields = ['text'] # 该表单只包含字段text 
        labels = {'text': ''} # 让Django不要为字段text 生成标签。


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        '''
        定义了属性widgets 。 小部件 （widget） 是一个HTML表单元素， 如单行文本框、 多行文本区域或下拉列表。 通过设置属性widgets ， 可覆盖Django选择的默认小
        部件。 通过让Django使用forms.Textarea ， 我们定制了字段'text' 的输入小部件， 将文本区域的宽度设置为80列， 而不是默认的40列。 这给用户提供了足够的空间， 可以
        编写有意义的条目。
        '''

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.http import HttpResponseRedirect,Http404    # 导入了异常Http404
from django.contrib.auth.decorators import login_required

from django.urls import reverse
# from django.core.urlresolvers import reverse
'''
https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers
Django 2.0 removes the django.core.urlresolvers module, which was moved to django.urls in version 1.10.
You should change any import to use django.urls instead, like this:
from django.urls import reverse
'''
# Create your views here. 在这里创建视图

def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

@login_required # Django提供了装饰器@login_required ， 让你能够轻松地实现这样的目标： 对于某些页面， 只允许已登录的用户访问它们
def topics(request):
    """显示所有的主题"""
    # topics = Topic.objects.order_by('date_added') # 查询数据库——请求提供Topic 对象， 并按属性date_added 对它们进行排序
    topics = Topic.objects.filter(owner=request.user).order_by('date_added') # 只向用户显示属于自己的主题
    context = {'topics': topics} # 一个将要发送给模板的上下文。 上下文是一个字典， 其中的键是我们将在模板中用来访问数据的名称， 而值是我们要发送给模板的数据。 
    return render(request, 'learning_logs/topics.html', context)

@login_required 
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added') # 获取与该主题相关联的条目， 并将它们按date_added 排序： date_added 前面的减号指定按降序排列， 即先显示最近的条目
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

# 函数new_topic() 需要处理两种情形： 刚进入new_topic 网页（在这种情况下， 它应显示一个空表单） ； 对提交的表单数据进行处理， 并将用户重定向到网页topics
@login_required 
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据： 创建一个新表单
        form = TopicForm()  # # 如果请求方法不是POST， 请求就可能是GET， 因此我们需要返回一个空表单
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)  # 创建一个TopicForm 实例,将其存储在变量form 中， 再通过上下文字典将这个表单发送给模板
        '''
        if form.is_valid(): # 必须先通过检查确定它们是有效的
            form.save() # 表单中的数据写入数据库
            # 函数reverse() 根据指定的URL模型确定URL， 这意味着Django将在页面被请求时生成URL。 
            # 调用HttpResponseRedirect() 将用户重定向到显示新增条目所属主题的页面
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        '''
        if form.is_valid(): # 将新主题关联到当前用户
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)
    '''
    创建Web应用程序时， 将用到的两种主要请求类型是GET请求和POST请求。 对于只是从服务器读取数据的页面， 使用GET请求； 在用户需要通过表单提交信息时， 通常使用POST
    请求。 处理所有表单时， 我们都将指定使用POST方法。 还有一些其他类型的请求， 但这个项目没有使用。
    函数new_topic() 将请求对象作为参数。 用户初次请求该网页时， 其浏览器将发送GET请求； 用户填写并提交表单时， 其浏览器将发送POST请求。 根据请求的类型， 我们可以
    确定用户请求的是空表单（GET请求） 还是要求对填写好的表单进行处理（POST请求） 。
    '''
@login_required 
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid(): 
            # 调用save() 时， 传递了实参commit=False , 让Django创建一个新的条目对象， 并将其存储到new_entry 中， 但不将它保存到数据库中。
            new_entry = form.save(commit=False)
            new_entry.topic = topic # 将new_entry的属性topic 设置为在这个函数开头从数据库中获取的主题
            new_entry.save()    # 调用save() ， 且不指定任何实参。 这将把条目保存到数据库， 并将其与正确的主题相关联。
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required 
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user: # 保护页面edit_entry
        raise Http404

    if request.method != 'POST':
        # 初次请求， 使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据， 对数据进行处理
        # 让Django根据既有条目对象创建一个表单实例， 并根据request.POST 中的相关数据对其进行修改
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--http://www.runoob.com/w3cnote/meta.html-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top"> <!--<nav> 元素， 表示页面的导航链接部分。-->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed">
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}">register</a></li>
                    <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>

</html>



<!--
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -
    在Django身份验证系统中， 每个模板都可使用变量user ， 这个变量有一个is_authenticated 属性： 如果用户已登录， 该属性将为True ， 否则为False 。
    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">register</a> - 
    <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

\{\% block content \%\}

\{\% endblock content \%\}
-->

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'> <!--实参action 将表单发回给函数edit_entry() 进行处理-->
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}

<div class='jumbotron'>
    <h1>Track your learning.</h1>
</div>
{% endblock header %}
{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</h2>
{% endblock content %}



<!--
\{\% extends "learning_logs/base.html" \%\}

\{\% block content \%\}
<p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
\{\% endblock content \%\}
-->

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
</form>

{% endblock content %}

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %} 
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
</form>
{% endblock content %}
<!--

{\% extends "learning_logs/base.html" %\}

{\% block content %\}

<p>Add a new topic:</p>
<定义了一个HTML表单>
<实参action 告诉服务器将提交的表单数据发送到哪里， 这里我们将它发回给视图函数new_topic() 。 实参method 让浏览器以POST请求的方式提交数据。>
<form action="{% url 'learning_logs:new_topic' %}" method='post'>  
    {\% csrf_token %\} <防止攻击者利用表单来获得对服务器未经授权的访问>
    {{ form.as_p }} <显示表单修饰符as_p 让Django以段落格式渲染所有表单元素， 这是一种整洁地显示表单的简单方式。>
    <button name="submit">add topic</button> <Django不会为表单创建提交按钮， 因此定义了一个这样的按钮。>
</form>

{\% endblock content %\}
-->

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
{% for entry in entries %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                    edit entry</a>
            </small>
        </h3>
    </div>
    <div class="panel-body">
        {{ entry.text|linebreaks }}
    </div>
</div> <!-- panel -->
{% empty %}
There are no entries for this topic yet.
{% endfor %}
{% endblock content %}

<!--
{\% extends 'learning_logs/base.html' %\}

{\% block content %\}
<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
    <a href="{\% url 'learning_logs:new_entry' topic.id %\}">add new entry</a>
</p>

<ul>
    {\% for entry in entries %\}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{\% url 'learning_logs:edit_entry' entry.id %\}">edit entry</a>
        </p>
    </li>
    {\% empty %\}
    <li>
        There are no entries for this topic yet.
    </li>
    {\% endfor %\}
</ul>

{\% endblock content %\}
-->

Python编程从入门到实践/learning_log/learning_log_ALL/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
<h1>Topics</h1>
{% endblock header %}
{% block content %}
<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</h3>
{% endblock content %}

<!--
{\% extends "learning_logs/base.html" %\}
<!使用标签\{\% extends \%\} 来继承base.html，>

{\% block content %\}
<p>Topics</p>
<ul>
    {\% for topic in topics %\}
    
    <!用了一个相当于for 循环的模板标签， 它遍历字典context 中的列表topics>
    <li>
        <a href="{\% url 'learning_logs:topic' topic.id %\}">{{ topic }}</a>
    </li>
    <!在模板中打印变量， 需要将变量名用双花括号括起来>
    {\% empty %\} <!注意 {% 没有空格>
    <!使用了模板标签\{\% empty \%\} ， 它告诉Django在列表topics 为空时该怎么办>
    <li>No topics have been added yet.</li>
    {\% endfor %\}
    <!必须使用\{\% endfor \%\} 标签来显式地指出其结束位置>

</ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>

{\% endblock content %\}
-->